# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59d1af30f048b3ca06decd60aa849903ad062c26166d249c691ee535cd49770f58b809fd77f4310edf7dad4fceefec70127bf7f45b4d5ee2e80feef7e09a387a

test:
  secret_key_base: e12553a8a1c2f25ce7ca23b5511d4565c14f2571034cf67609f92850459eab2a64a5a8da8f22b88507c1881db9ecb494012fca12e3d9f4684f66fb5a37e45b6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
